spring:
  security:
    oauth2:
      authorizationserver:
        client:
          api-client:
            registration:
              client-id: api-client
              client-secret: "{noop}secret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              scopes:
                - api.read
                - api.write
            token:
              access-token-format: self-contained
              access-token-time-to-live:
                seconds: 300 # 5 minutes
              refresh-token-time-to-live:
                seconds: 3600 # 1 hour
              id-token-signature-algorithm: RS256

