spring:
  config:
    import:
      - optional:classpath:oauth_clients.yml
      - optional:classpath:config/security.yml
      - optional:classpath:config/oauth2_clients.yml


  application:
    name: mm-oauth-server

  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.schema-generation.database.action: none
      javax.persistence.schema-generation.create-source: none

  flyway:
    enabled: false
    locations: classpath:db/migration

  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/DDL/*.sql
      data-locations: classpath:db/migration/DML/*.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      authorizationserver:
        issuer: "http://localhost:9000"
        client:
          api-client:


server:
  port: 9000
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web.client: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info